let modelsList = [
  {
    id: 1,
    name: "Iphone 11",
    img: "img/marcas/iphone11.white.jpg",
    prices: [4000, 4000, 4000],
    sizes: ["42cm", "48cm", "54cm"],
    description:"Milky White.",
  },
  {
    id: 2,
    name: "Iphone 11",
    img: "img/marcas/iphone11.jpg",
    prices: [4100, 4100, 4100],
    sizes: ["42cm", "48cm", "54cm"],
    description:"Serious Black.",
  },
  {
    id: 3,
    name: "Iphone 11",
    img: "img/marcas/iphone11.blue.jpg",
    prices: [3654.25, 3654.25, 3654.25],
    sizes: ["42cm", "48cm", "54cm"],
    description:"Subway Blue.",
  },
  {
    id: 4,
    name: "Iphone 11",
    img: "img/marcas/iphone11.red.jpg",
    prices: [3654.25, 3654.25, 3654.25],
    sizes: ["42cm", "48cm", "54cm"],
    description:"Product RED.",
  },
  {
    id: 5,
    name: "Short Moletom Nike Essential Nsw FT",
    img: "img/marcas/Bermuda_Nike.jpg",
    prices: [142.90, 142.90, 142.90],
    sizes: ["P", "M", "G"],
    description:"Fabricado com tecido macio ao toque da pele, o modelo tem cós elástico e cordão para ajuste eficaz; bolsos laterais podem ser usados para guardar pequenos objetos e deixam suas mãos livres para você se movimentar.",
  },
  {
    id: 6,
    name: "Bermuda Adidas Run It Pb",
    img: "img/marcas/Bermuda_Adidas.jpg",
    prices: [139.99, 139.99, 139.99],
    sizes: ["P", "M", "G"],
    description:"Produzido com material leve, conta com tecnologia que absorve o suor da pele e te mantem seco durante suas séries mais intensas.",
  },
  {
    id: 7,
    name: "Short Asics 4IN Icon Performance",
    img: "img/marcas/Bermuda_Ascis.jpg",
    prices: [129.99, 129.99, 129.99],
    sizes: ["P", "M", "G"],
    description:"O Short ASICS 4IN Icon Performance foi projetado com um tecido leve equipado com propriedades eficazes de absorção de umidade.",
  },
  {
    id: 8,
    name: "Bermuda Puma Active 5",
    img: "img/marcas/Bermuda_Puma.jpg",
    prices: [142.90, 142.90, 142.90],
    sizes: ["P", "M", "G"],
    description:"Além de moderno e funcional, possui construção em 100% poliéster reciclado com modelagem regular fit e conta com cós elástico com cordão interno",
  },
  {
    id: 9,
    name: "Camiseta Nike Sportwear Icon Futura",
    img: "img/marcas/Camisa_Nike.jpg",
    prices: [74.99, 74.99, 74.99],
    sizes: ["P", "M", "G"],
    description:"Com o icônico logo da Nike estampado em destaque, essa camiseta masculina é a pedida certa para quem curte manter um visual confortável e casual. Esteja preparado e bem vestido em qualquer situação.",
  },
  {
    id: 10,
    name: "Camiseta Adidas Aeroready Off White",
    img: "img/marcas/Camisa_Adidas.jpg",
    prices: [199.90, 199.90, 199.90],
    sizes: ["P", "M", "G"],
    description:"Camiseta manga curta, gola redonda. com logo frontal.",
  },
  {
    id: 11,
    name: "Camiseta Puma Power Aop",
    img: "img/marcas/Camisa_Puma.jpg",
    prices: [99.90, 99.90, 99.90],
    sizes: ["P", "M", "G"],
    description:"Confeccionada em algodão, a peça com estampa full print oferece versatilidade para combinar com calça jeans ou bermuda e te deixando pronto para trabalhar ou curtir os momentos de lazer. ",
  },
  {
    id: 12,
    name: "Camiseta Reebok Cl D Vector Repeat Tee",
    img: "img/marcas/Camisa_Reebok.jpg",
    prices: [69.99, 69.99, 69.99],
    sizes: ["P", "M", "G"],
    description:"A camiseta ideal para todos os momentos, aquela que garante conforto e segurança para se mover livremente e que é a combinação perfeita entre desempenho e conforto.",
  },
  {
    id: 13,
    name: "Calça Adidas Essentials Slim 3 Listras",
    img: "img/marcas/Calca_Adidas.jpg",
    prices: [137.74, 137.74, 137.74],
    sizes: ["P", "M", "G"],
    description:"Calça Adidas Essentials Slim 3 Listras Feminina.",
  },
  {
    id: 14,
    name: "Calça Moletom Nike Tapered",
    img: "img/marcas/Calca_Nike.jpg",
    prices: [199.99, 199.99, 199.99],
    sizes: ["P", "M", "G"],
    description:"Produzida com material macio ao toque e modelagem mais larguinha, a peça possui ainda tecnologia que afasta o suor da pele e te mantém seco e confortável entre uma série e outra.",
  },
  {
    id: 15,
    name: "Calça Legging Puma Graphic",
    img: "img/marcas/Calca_Puma.jpg",
    prices: [90.24, 90.24, 90.24],
    sizes: ["P", "M", "G"],
    description:"O tecido leve e macio fornece conforto e flexibilidade durante os exercícios, enquanto o design moderno garante excelente modelagem ao corpo.",
  },
  {
    id: 16,
    name: "Calça ASICS Stretch",
    img: "img/marcas/Calca_Asics.jpg",
    prices: [199,99, 199,99, 199,99],
    sizes: ["P", "M", "G"],
    description:"A Calça ASICS Stretch foi projetada com um tecido repelente de água para mantê-la seca e confortável durante seus treinos.",
  },
  {
    id: 17,
    name: "Tênis Nike Air Max Bella TR 4",
    img: "img/marcas/Tenis_Nike.jpg",
    prices: [341.99, 341.99, 341.99],
    sizes: ["36", "37", "38"],
    description:" O Air Max oferece amortecimento enquanto você foca no jogo, já o cabedal em mesh auxilia na maciez e ventilação interna. O cano médio proporciona um ajuste macio ao redor do tornozelo e o solado emborrachado garante resistência à abrasão.",
  },
  {
    id: 18,
    name: "Tênis Adidas Runfalcon 2.0",
    img: "img/marcas/Tenis_Adidas.jpg",
    prices: [179.99, 179.99, 179.99],
    sizes: ["40", "41", "42"],
    description:"O Runfalcon 2.0 chega com um cabedal com tripla camada de mesh para ainda mais respirabilidade, calcanhar acolchoado para máximo conforto e suporte, além de uma entressola em EVA para amortecimento leve e passada mais suave.",
  },
  {
    id: 19,
    name: "Tênis Asics Gel-Excite 8",
    img: "img/marcas/Tenis_Ascis.jpg",
    prices: [299,99, 299,99, 299,99],
    sizes: ["36", "37", "38"],
    description:"O Excite 8 conta com cabedal fabricado com material respirável e cortes em material sintético para suporte. A entressola em EVA oferece amortecimento leve e traz a famosa tecnologia Gel que garante absorção de impactos. Já o solado emborrachado te dá segurança e tração em diferentes tipos de piso. Treine em busca do melhor pace usando o running Asics.",
  },
  {
    id: 20,
    name: "Tênis Reebok Npc Ii",
    img: "img/marcas/Tenis_Reebok.jpg",
    prices: [419,99, 419,99, 419,99],
    sizes: ["40", "41", "42"],
    description:"Nosso NPC II all-white dominou as quadras nos anos 80 e, hoje, ele se tornou um ícone.",
  },
];
